- name: Cleanup green version
  become: yes
  shell: |
    kubectl get deployment -o name | grep "devops5-backend" | grep $CIRCLE_WORKFLOW_ID \
    | while read OldDeployment; 
      do
        kubectl delete $OldDeployment
        echo "Clean ${OldDeployment}"
      done
- name: Cleanup green service
  become: yes
  shell: |
    kubectl get service -o name | grep "devops5-backend-green" \
    | while read GreenService; 
      do
        kubectl delete $GreenService
        echo "Clean ${GreenService}"
      done
- name: Cleanup k8s files
  become: yes
  shell: |
    rm -rf /home/ubuntu/k8s/
