apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops5-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops5-backend-$CIRCLE_WORKFLOW_ID
  template:
    metadata:
      labels:
        app: devops5-backend-$CIRCLE_WORKFLOW_ID
    spec:
      containers:
      - name: devops5-backend-$CIRCLE_WORKFLOW_ID
        image: kienndt/devops5-be:$CIRCLE_WORKFLOW_ID
        ports:
        - containerPort: 3030