apiVersion: v1
kind: Service
metadata:
  name: devops5-backend-green
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3030
    targetPort: 3030
    nodePort: 30033
  selector:
    app: devops5-backend-$CIRCLE_WORKFLOW_ID