version: 2.1
      
# commands:
#   destroy-environment:
#     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
#     parameters:
#       # Add parameter here
#       when:
#         type: string
#       id:
#         type: string
#     steps:
#       - run:
#           name: Destroy environments
#           when: on_fail
#           command: |
#             aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.id >>
#             aws s3 rm s3://udapeople-<< parameters.id >> --recursive
#             aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.id >>
#   revert-migrations:
#     parameters:
#       when:
#         type: string
#       id:
#         type: string
#     steps:
#       - run:
#           name: Revert migrations
#           when: on_fail
#           command: |
#             cd backend
#             SUCCESS=$(curl -H "token: udacity-project3-devops" --request GET http://ec2-34-230-47-86.compute-1.amazonaws.com:3000/DB_MIGRATION_<< parameters.id >>)
#             echo $SUCCESS
#             if [[ "$SUCCESS" == "success" ]]
#             then
#               npm run migrations:revert
#             fi

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            export API_URL=""
            echo "${API_URL}"
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Front-end test
          command: |
            cd frontend
            npm install jest
            npm run test
                
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end test
          command: |
            cd backend
            npm install jest
            npm run test
    
  build-dockerimage:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:   
      - checkout   
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build backend image
          command: |
            echo "$DOCKERHUB_PASSWORD"
            docker login -u $DOCKERHUB_USERNAME -p "$DOCKERHUB_PASSWORD"
            cd ./backend
            echo "NODE_ENV=production" >> .env
            echo "TYPEORM_CONNECTION=${TYPEORM_CONNECTION}" >> .env
            echo "TYPEORM_ENTITIES=${TYPEORM_ENTITIES}" >> .env
            echo "TYPEORM_HOST=${TYPEORM_HOST}" >> .env
            echo "TYPEORM_PORT=${TYPEORM_PORT}" >> .env
            echo "TYPEORM_USERNAME=${TYPEORM_USERNAME}" >> .env
            echo "TYPEORM_PASSWORD=${TYPEORM_PASSWORD}" >> .env
            echo "TYPEORM_DATABASE=${TYPEORM_DATABASE}" >> .env
            echo "TYPEORM_MIGRATIONS=${TYPEORM_MIGRATIONS}" >> .env
            echo "TYPEORM_MIGRATIONS_DIR=${TYPEORM_MIGRATIONS_DIR}" >> .env
            docker build -t devops5-be:lastest .
            docker tag "devops5-be:lastest" "kienndt/devops5-be:${CIRCLE_WORKFLOW_ID:0:7}"
            docker push "kienndt/devops5-be:${CIRCLE_WORKFLOW_ID:0:7}"

  deploy-backend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["87:b6:37:6b:09:db:10:6f:96:75:e9:78:9c:47:7b:de"]
      - run:
          name: Install dependencies
          command: |
            yum install -y tar gzip python3 openssh openssh-clients
            python3 -m pip install ansible==2.9.22
            ansible --version
      - run:
          name: Run deploy job
          command:
            ansible-playbook -i inventory.txt deploy-backend.yml -vvv

workflows:
  default:
    jobs:
      # - build-dockerimage
      - deploy-backend
