- name: Delete old k8s deploy files
  become: yes
  shell: |
    rm -rf /home/ubuntu/k8s/
- name: Copy k8s deploy files
  become: yes
  copy:
    src: ../k8s/
    dest: /home/ubuntu/k8s/
- name: Deploy new backend
  become: yes
  shell: |
    cd /home/ubuntu/k8s/
    envsubst < backend-deployment.yml | kubectl apply -f -
    envsubst < backend-service-green.yml | kubectl apply -f -
    kubectl wait deploy/devops5-backend-$CIRCLE_WORKFLOW_ID --for condition=available --timeout=600s
