- name: Cleanup old blue version
  become: yes
  shell: |
    kubectl get deployment -o name | grep "devops5-backend" | grep -v $CIRCLE_WORKFLOW_ID \
    | while read OldDeployment; 
      do
        kubectl delete deployment $OldDeployment
        echo "Clean ${OldDeployment}"
      done
